[package]
name = "PassworldCrack"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust-crypto = "0.2.36"
rand = "0.7"
base64 = "0.10"
chrono = "0.4.23"
futures = "0.3"